/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qualifications` | `/qualifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/share` | `/share`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/table` | `/table`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test-supabase` | `/test-supabase`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/qualifications` | `/qualifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/share` | `/share`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/table` | `/table`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/test-supabase` | `/test-supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/companies${`?${string}` | `#${string}` | ''}` | `/companies${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/qualifications${`?${string}` | `#${string}` | ''}` | `/qualifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/share${`?${string}` | `#${string}` | ''}` | `/share${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/table${`?${string}` | `#${string}` | ''}` | `/table${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/test-supabase${`?${string}` | `#${string}` | ''}` | `/test-supabase${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qualifications` | `/qualifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/share` | `/share`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/table` | `/table`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test-supabase` | `/test-supabase`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
